### ISSUE TITLE
Why are these images necessary?

### ISSUE THREAD

**Issue by codecowboy** [spurin/container-systemd#2]
@spurin  Can you explain why you went to the trouble of creating these images when the DiveIntoAnsible course would work fine with just standard base images from dockerhub? I don't understand why a custom systemd implementation is useful / desired. Is it just to emulate a 'real' tty login experience? Is it required for the browser-based terminals? I'm genuinely curious to know (I dont know much about deep linux internals) and this is not intended as a criticism of the course - I'm following it on Udemy to brush up my ansible skills and it seems very thorough so far. Thanks!

**Comment by spurin** [comment]
Hi @codecowboy 

Nice question. The custom images with systemd provide a heap of benefits. As they are using systemd we're able to mimic a VM, rather than a container which would typically run a single process. This gives us a lot of the functionality that you'd expect from a VM.

Granted, whilst you'll be able to do some areas in a standalone ubuntu or centos container, there's others that you couldn't.

A nice example is being able to enable/restart/stop/start services after you've installed a particular package (for example, nginx). Systemd is a standard for most modern Linux systems in this respect.

Outside of this, it's convenient for other services that Ansible depends upon. For example, sshd which again, runs and is managed via systemd.

Since the system is more like a VM than a traditional single process container image, it's also great for running other services like those used by the lab environment (web terminals).

Hopefully this helps!

**Comment by codecowboy** [comment]
Thanks - that's very helpful. I have mostly used VMs and containers as local development environments using pre-built images or creating my own with Virtualbox / Vagrant. Having just looked at the  the Dockerfile and entrypoint scripts in the nginx repository (and yours here) I now have a better appreciation for the amount of configuration involved in creating the base images for docker containers. I also hadn't realised that containers are often running what I thought of as services as foreground processes. Thanks for taking the time to explain your rationale - much appreciated.
